export const chairsData = [
  {
    id: "SFCHAIR01",
    name: "Office chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-1.jpeg",
      "/assets/chair-section/chair-image-2.jpeg",
      "/assets/chair-section/chair-image-2.jpeg",
      "/assets/chair-section/chair-image-2.jpeg",
      "/assets/chair-section/chair-image-2.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR02",
    name: "Brio net chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-2.jpeg",
      "/assets/chair-section/chair-image-2.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR03",
    name: "Net matrix high back",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-3.jpeg",
      "/assets/chair-section/chair-image-3.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR04",
    name: "Net 500 medium back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-4.jpeg",
      "/assets/chair-section/chair-image-4.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR05",
    name: "Office high & medium back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-5.jpeg",
      "/assets/chair-section/chair-image-5.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR06",
    name: "Net medium back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-6.jpeg",
      "/assets/chair-section/chair-image-6.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR07",
    name: "Net Matrix medium back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-7.jpeg",
      "/assets/chair-section/chair-image-7.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR08",
    name: "Office high back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-8.jpeg",
      "/assets/chair-section/chair-image-8.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
  {
    id: "SFCHAIR09",
    name: "Octiva Pandey high back chair",
    type: "Revolving chair",
    images: [
      "/assets/chair-section/chair-image-9.jpeg",
      "/assets/chair-section/chair-image-9.jpeg",
    ],
    arm: true,
    armMaterial: "Arm material",
    backColor: "black",
    backMaterial: "Net matrix",
    seatColor: "black",
    seatMaterial: "net matrix",
    stand: "Chair stand",
    wheel: "chair wheel",
    heightAdjustable: "height adjuastable details",
    headrest: true,
    price: "2000",
  },
];
